# Generated by Django 5.1 on 2024-09-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadminapp', '0004_alter_department_head_of_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Media/Profile_pic')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Media/Profile_pic')),
            ],
        ),
    ]
