# Generated by Django 5.1 on 2024-09-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadminapp', '0005_base'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base',
            options={'verbose_name': 'Base', 'verbose_name_plural': 'Base'},
        ),
    ]
