# Generated by Django 5.1 on 2024-09-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadminapp', '0007_alter_base_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Base',
        ),
    ]
